1090es_relay.go
extract_metar.go
gen_gdl90.go

Just ran the code through gofmt.
BTW, this is the same joe from reddit.

gofmt format changes

---

gen_gdl90.go

Sorry for the ongoing format changes; my editor runs gofmt automatically when the file is saved.

remove redundant trim op, comment update

---

gen_gdl90.go

just the one addition and gofmt

set GOMAXPROCS to core count (Go v1.5 now does this automatically)

---

1090es_relay.go
gen_gdl90.go
ry835ai.go

...low-hanging fruit, I know. :/

concurrent safe log package for printing, don't remake buf in gpsSerialReader loop

---

.gitignore
Makefile
gen_gdl90.go

Move management IP to config
Use normal go for building rather than an alias
Build 1090es relay via Makefile

misc minor tweaks

---

main/gen_gdl90.go
web/index.html
web/js/stratux.js

changed the UTime to be a value and now handle all formatting in the webUI
render the CPU temp in the webUI

webUI update for time and temp

---

main/gen_gdl90.go
web/index.html
web/js/stratux.js

known issue with this still: not resetting to zero after a product is no longer sent by the server.

show which types of uat messages we've gotten

---

main/ry835ai.go

also a gofmt run over the file

shift direction fix

---

web/css/main.css
web/plates/js/weather.js
web/plates/settings.html
web/plates/status.html
web/plates/weather.html

added the NOAA flight condition color coding. There may be fringe conditions but the fall back is to not add color
weather is now marked by "age" as in how old it is. I had to test using playback so this should get flight tested before the next "release"
the status page now has message graphs (current as a percentage of peak)

color coded METARs; time 'old' for weather; and message volume bar graph

---

main/managementinterface.go
web/index.html
web/js/main.js
web/plates/js/status.js
web/plates/js/towers.js
web/plates/js/traffic.js
web/plates/status.html
web/plates/towers-help.html
web/plates/towers.html

created new towers details page but its currently commented out of the WebUI as it may not be sufficiently useful
added active tower count to primary status page
created status web servcie for cases wehre a single instance is needed

created new towers details page and towers status on main page

---

main/gen_gdl90.go

This change will move the log files to /var/log/stratux, and each file set will start with an incrementing number 0000,0001,0002, etc
This enables the .gz compression to work properly since each session now has its own log files

Added indexed logs instead of everything ending up in one file

---

main/managementinterface.go
web/plates/status.html

Added a couple of functions to handle rebooting and shutdown of the PI from the status screen.
This is a first attempt at contributing to a project so I wanted to keep it simple in the hopes that I did this correctly.

Shutdown and Reboot functions

---

main/traffic.go

simplified calculation with proper invalid altitude handling

fixed altitude calculation as per GDL 90 data interface spec

---

main/network.go
main/sdr.go

Turn down UAT capture to 10% duty cylce when message rate is 0.

---

.gitmodules
Makefile
circle.yml
main/ry835ai.go
mpu6050/mpu6050.go
test/sensortest.go

Uses DMP "Digital Motion Processor" functions of MPU6050/MPU9150.

Integrate linux-mpu9150 for AHRS.

---

main/ry835ai.go

Fixes #177. Validated on U-blox 7 (VK-172).

Check for valid GPS date. Fix time string formatting.

---

main/ry835ai.go

GPS time zone fix. Don't assume Pi is set to UTC.

---

web/plates/js/settings.js
web/plates/settings.html

Per 193 - modified shutdown and reboot functions to be POST requests.
Put shutdown and reboot buttons in their own areas to reduce chances of accidentally hitting the wrong button.
Added post shutdown/reboot messages.

Updated shutdown

---

.gitignore
Makefile
init.d-stratux
main/gen_gdl90.go

Now that we have consolidated gen_gdl90 and no longer need the nested start scripts, we can start/stop the main process directly from the init.d script. 
This means /etc/init.d/stratux stop will work correctly :-)

start/stop gen_gdl90 directly fron init.d-stratux

---

web/css/main.css
web/plates/js/logs.js
web/plates/js/settings.js
web/plates/logs-help.html
web/plates/logs.html
web/plates/settings.html

added missing logs help page, 
adjusted settings page layout across different devices sizes
added basic filename checking for updates - eg: name must start with 'update' and have '.sh' extention, cleaned up the interface for uploading an update ... at least a little

some web ui cleanup

---

image/interfaces

Added settings to /etc/network/interfaces as a template for a second wifi dongle for dev work

Second wifi dongle settings template for Dev work

---

main/sdr.go

apologies for the excess list of commits, somehow something got out of sync...

sdr: when cmd.Start fails use the proper shutdown procedure

---

main/managementinterface.go
main/sdr.go

Also capture global state info at start of config process

sdr: fix 1090 shutdown hang, add shutdown completed messages

---

web/plates/status.html

Also added in a `className` so the messages can be explicitly styled later, although that may not be necessary.

Tweak error messages to use FontAwesome icon and stock angular maui colors.

---

image/hostapd_manager.sh

This is a improvement on the script that was uploaded to reddit. 
https://www.reddit.com/r/stratux/comments/4c0ffw/change_ssid_bash_script/
Help documentation for go.sh.
Basic usage: hostapd_manager.sh -s ssid -c chan -e pass
Command line switches are optional. The following switches are recognized.
-s  --Sets the SSID to ssid. "-s stratux"
-c  --Sets the channel to chan. "-c 1"
-e  --Turns on encryption with passphrase pass. 8-13 Printable Characters. Cannot be used with -o. "-e password!"
-o  --Turns off encryption and sets network to open. Cannot be used with -e.
-h  --Displays this help message. No further functions are performed.
Example: hostapd_manager.sh -s stratux -c 1 -e N3558D
I am sure there are many places where this file can be optimized but this is what I can do!!
Feel free …

Bash script to modify hostapd.conf and hostapd-edimax.conf

---

main/datalog.go
main/gen_gdl90.go
main/managementinterface.go
main/plugin.go
main/ry835ai.go
main/sdr.go
main/traffic.go
selfupdate/update_header.sh

* Improved buffering.
* Batched queries.
* Only log sentences for which `processNMEALine()` returns true by default unless `globalSettings.DEBUG` is true.
* Traffic logging.

Sqlite logging.

---

image/mkimg.sh

copy file to location and chmod

Update mkimg.sh for hostapd_manager.sh

---

image/bashrc.txt

Since I am tired of my aliases being over written I am adding this so I can make my own alias file and not have it overwritten!!!!!!!!!!!!!
create a file called .aliases in /root and they will be included

keep an alias file after this file is modified and Stratux Specific Aliases

---

selfupdate/makeupdate.sh

adding the lines to include stxAliases and hostapd_manager.sh to makefile

Add aliases and hostapd_manager.sh

---

main/managementinterface.go
web/js/main.js
web/plates/js/settings.js

1. changed the POST request for /reboot to redirect to the Status page and wait for Stratux to reboot
2. changed managementinterface for reboot to return a header for the POST operation and to spawn the reboot so the POST reply will complete

trigger reboot as a webservice and redirect webui to status page

---

image/stxAliases.txt

Typo in stxAliases.txt

---

selfupdate/update_footer.sh

I don't know if this was an oversight but I believe this should of been included

include hostapd-edimax.conf along with hostapd.conf during updates

---

image/stratux-wifi.sh

Adds a serial check for the board released second quarter of 2016

Add support for RPi0 board rev 1.3

---

main/traffic.go

Intial prototype for ownship traffic suppression

---

main/ry835ai.go

Ref #487. 
Ublox-7 firmware has bug in handling of GPS height-above-ellipsoid reports in PUBX,00 message; negative altitudes are floored at zero. Manifests as GPS altitude floor of 70-100' MSL over most of North America.
Workaround is pulling altitude data from GGA message if HAE == 0.

Workaround to allow negative GPS HAE on ublox-7

---

main/gen_gdl90.go
web/plates/js/status.js
web/plates/status.html

Feel free to tweak to your liking

Added UAT statistics to the status page

---

main/gen_gdl90.go
main/managementinterface.go
web/index.html
web/js/main.js
web/maui/css/mobile-angular-ui-hover.css
web/plates/developer-help.html
web/plates/developer.html
web/plates/js/developer.js
web/plates/js/settings.js
web/plates/js/status.js
web/plates/settings.html
web/plates/status.html

Handles a developer mode, with a reload function in the developer menu
Also can enter development mode by clicking the version 7 times in 3 seconds :)

Developer mode flag handling

---

web/js/main.js
web/plates/js/status.js

Fixed typo with developer mode variable

---

main/managementinterface.go

Will save the developermode when its activated via the web interface

This saves developermode to settings when it is activated

---

web/plates/status.html

Fixed alignment of UAT statistics of status page

Updated UAT statistics

---

web/css/main.css

I changed the font weight for 'body' because on a tablet/phone the text was hard to read on the web status page

A font you can actually read on a tablet/phone

---

README.md

Added a simple note that this version supports pingEFB as an ADS-B receiver.

Add pingEFB text to README

---

web/css/main.css
web/maui/css/mobile-angular-ui-base.css
web/plates/weather.html

Little better appearance tweaks - you may or may not like them

Church up weather status page

---

main/gen_gdl90.go
main/managementinterface.go
main/ry835ai.go
main/traffic.go
main/uibroadcast.go
uatparse/nexrad.go
uatparse/uatparse.go

For our avare port, the developers want it in

Stratux websocket support. NEXRAD decoding added to uatparse.

---

main/gen_gdl90.go
main/managementinterface.go
main/network.go
main/ry835ai.go

makes the web interface very responsive

Move timer calls to bottom of routines

---

main/gpsd.go

* Discard 2d fixes from gpsd
* Log invalid modes and discard

gpsd: Discard 2D GPS fixes.

---

__root__stratux-pre-start.sh
image/hostapd_manager.sh
image/stratux-wifi.sh

1) Changed the location of the code that checks and created the new hostapd file structure to execuite after ifup wlan0. Along with moving the code to stratux-wifi.sh, I changed to format of stratux-wifi.sh to work in functions so the code can stay compartmentalized for each task. 
2) I tried and tried for hours to get encryption to work with the edimax dongle. 
Since I could not get it, I removed(commented the code out so it was not lost)  the code from my hostpad_manager.sh script so it cannot be added. 
The hostapd_manager.sh script can now only change the SSID and/or channel

Wifi lag fix

---

image/interfaces

Seems this is useful now that we have the static IP option in developers

Added allow-hotplug eth0

---

image/10-stratux.rules

udev rule for SoftRF  [**Dongle Edition**](https://github.com/lyusupov/SoftRF/wiki/Dongle-Edition) .

UDEV rule for SoftRF Dongle Edition

---

web/plates/gps.html
web/plates/js/gps.js

Add GPS height above WGS-84 ellispoid to the website.
Signed-off-by: PepperJo <pepperjo@japf.ch>

Website: Add height above ellipsoid

---

main/gen_gdl90.go
main/managementinterface.go
web/css/dark-mode.css
web/css/main.css
web/index.html
web/js/main.js
web/plates/js/settings.js
web/plates/settings.html
web/plates/status.html

This PR adds dark mode UI mode.  The current UI is very bright, especially during night ops.  This maintains the original UI styling as the default and adds a "Dark Mode" option on the settings page. Please see attached images of the UI in dark mode:

Add dark mode
