main/managementinterface.go

the new REST services for getting and setting the current set of user accessible settings include:
UAT_Enabled    bool
ES_Enabled     bool
GPS_Enabled    bool
AHRS_Enabled   bool
DEBUG          bool
ReplayLog      bool
PPM            int
All of the existing REST services have been made to support cross-domain AJAx calling.
The above is in support of the new WebUI (to be submitted as follow-on branch). Once the new WebUI is committed, some of the existing data on the websocket should be deprecated.

New REST services with getter/setter for settings

---

main/gen_gdl90.go
main/managementinterface.go
web/plates/js/settings.js
web/plates/js/status.js
web/plates/js/weather.js
web/plates/settings-help.html
web/plates/settings.html

The OwnShipModeS value is assumed to come in as string (HEX) but goes back out as an integer, this really messes with the normal processing of configuration settings. Since teh HEX string is eas yfor users to enter in the UI, it made sense to preserve that in the UI and in the stratux.conf file. Therefore, it becomes necessary to work wit hthe HEX string in the Go code.
I was able to test all of the GO code with the exception of the makeOwnshipReport();
There was an issue when attempting to clear the WeatherList. It would not allow the list to be reset back to 'blank'. I updated the validation code to handle this. I also now detect field focus changes to trigger validation and storage rather than just triggering from the 'form submit' event.

add OwnshipModeS to UI; tweaked Settings field validation

---

main/gen_gdl90.go
web/plates/js/status.js
web/plates/status.html

1) Adds "DGPS (WAAS)" vs "3D GPS" status to webUI status page. 
2) Change unit casting on ownship altitude such that negative pressure altitudes are properly displayed.

Add WAAS status to webUI. Correct unit casting error on ownship alt.

---

Makefile
test/Makefile

Fixed for circleci. This makefile makes sure GOROOT is checked, also will build 'test' applications if 'make test' is issued

Makefile build test

---

README.md
main/gen_gdl90.go
main/ry835ai.go
web/plates/gps.html
web/plates/js/gps.js
web/plates/js/status.js
web/plates/status.html

Multiple changes to GPS handling. 
- Configure GNSS and NMEA messages at cold startup
- Fixed byte-order bug on UART configuration
- Set UART bit rate to 38400 bps. (Prevents message drops at 9600 bps / 10Hz; more reliable than higher rates)
- Add validation of NMEA message checksums
- Add support for u-blox 'PUBX' NMEA messages to reduce bandwidth requirement and simplify future satellite constellation parsing
- Improved horizontal accuracy calculation
- Add vertical velocity and vertical accuracy; update UI 'GPS/AHRS' page
- Add satellites tracked and satellites seen; update UI 'Status' page
Changes tested on u-blox M8 (RY835AI UART) and u-blox 7 (VK-172 USB). Should be compatible with all u-blox 6, 7, and 8 series GPS.

Updated GPS initialization and parsing

---

main/ry835ai.go
web/plates/logs.html

1. Added 250 ms delay after GPS initialization / setup. This will let it "settle" at 38.4 kbps before opening the port to read NMEA messages. This seems to solve the "extended ASCII" errors we were seeing.
2. Add links to /logs/stratux.log and /logs/stratux/ to "Logs" page of web UI.

Delay start of UART reads. Link dev logs to web UI.

---

web/plates/js/traffic.js
web/plates/traffic.html

Update traffic.js to parse "Speed_valid" before writing ground speed. If speed is invalid, display "---" instead of "0".
Update rounding to show alt in 25' incremenents, and GS/heading in increments of 5 units.

Fix webUI zero GS bug

---

dump978/uat_decode.c

the code at mutability/dump978 posted a fix for a typo in the base 40 decode. the 'S' and 'T' letters were transposed in the reference string.
reference: https://github.com/mutability/dump978/commit/564902f53b0da7b095ccc5bf2ff28dda433372dd

Fix transposed S/T in base40 decoding

---

main/ry835ai.go

GPS and AHRS improvements:
* setTrueCourse() calls updated to put variables in the correct order. AHRS heading will no longer be set to groundspeed.
* Increased gain of GPS track correction to help overcome AHRS heading drift
* Added parsing of NMEA "GSA" messages as fallback for generic GPS receivers.

AHRS heading improvements. "Fallback" GPS message parsing

---

main/gen_gdl90.go
main/monotonic.go

Fixes #223, which was caused by an incorrect variable order in HumanizeTime().
Changes monotonic ticks from 1 second to 50 millisecond intervals (supports some back-end changes on my development branch). Uptime status report in gen_gdl90.go updated.

Fix #223. Change ticker to 50 ms intervals for future improvements.

---

main/gen_gdl90.go
main/ry835ai.go

Fixes #235.
This change detects if it's been more than five seconds since a valid NMEA message has been received.
If so, solution status is changed to "Disconnected", mySituation.quality and satellite counts are zeroed, and we break out of the gpsSerialReader() routine. This allows the GPS to reinitialize without spawning multiple instances of this goroutine.

Detect disconnected GPS. Update web UI and attempt reconnect.

---

main/gen_gdl90.go
main/ry835ai.go

**Add support for velocity and heading on pre-NMEA v2.3 receivers.** 
- NMEA v2.3 added 10th field ("posMode") to the VTG track / speed message; it's not used by Stratux, but the NMEA parser would not accept VGT messages with fewer than 10 fields.
- This change adds support for pre-2.3 receivers (e.g.  Delorme Earthmate LT-40).
**Resolve a stability issue related to disconnecting and reconnecting GPS hardware.** 
- The GPS tty port reader is initialized without a no-read timeout, so gpsSerialReader() gets blocked when a GPS is disconnected. This prevents the routine from exiting properly. When combined with the reconnect method introduced at 41b091f, this inadvertently caused "old" gpsSerialReader() routines to be orphaned without closing. This effectively created a resource leak every …

GPS improvements: Support velocity / heading on older receivers; resolve stability issue related to disconnects

---

main/ry835ai.go

1. Cleaned up groundspeed detection routines to improve consistency of reporting. Groundspeed will now be reported any time a valid speed is parsed. True course will be updated only when groundspeed > 3 knots. Method is now consistently applied to all source message types (PUBX,00, VTG, and RMC).
2. Add missing `LastFixLocalTime` and `LastGroundFixTime` updates to VTG and RMC parsers to improve compatibility with older / generic NMEA receivers. A minimum of RMC + GSA are all that's needed to generate a valid 2D fix, including speed / track. 3D position still requires GGA messages.
3. Quality and position accuracy are now parsed prior to position reports, rather than in NMEA sentence order. This allows values to be updated prior to returning on a bad / missing position, and ensures that …

Additional GPS compatibility improvements

---

main/gen_gdl90.go
main/network.go
main/ry835ai.go
main/traffic.go

These changes improve network message efficiency, and are a possible solution to some of the disconnect problems described in #246.
Testing with both UAT replay and simulated traffic data indicates that wlan0 does not handle high IO rates well. Details of this testing will be posted to #246. Although I didn't determine whether this was a go issue, a wlan driver issue, or a hardware / power issue, I did find opportunities to optimize both the queued and nonqueued message senders.
- Traffic data is now passed to `sendGDL90()` in a single message for each call to sendTrafficUpdates(), rather than as sequential individual reports. This has no effect on timing of traffic data, but greatly improves IO efficiency. With two ForeFlight clients connected, I found that the wlan connection would drop …

Networking improvements

---

init.d-stratux
main/sdr.go

Allows for per-SDR PPM information.
- Legacy support for stratux:978 and stratux:1090 is preserved
- SDRs without a specified PPM get the globalSettings PPM as configured on the Settings page
- Because the serial number field is length-constrained, the preferred format with PPM is stx:freq:ppm, such as stx:1090:20. Per peepsnet's question below, negative PPMs are supported; example: stx:1090:-20
- The PPM parser and the frequency designator are independent entities. If you don't need to specify a frequency, pick any number other than 978 and 1090 (0 recommended), and Stratux will assign frequencies. (Per peepsnet's second question below). Example: stx:0:-20

Fix for Issue #79

---

main/gen_gdl90.go
main/ry835ai.go
main/traffic.go
web/plates/js/status.js
web/plates/js/traffic.js
web/plates/status-help.html
web/plates/status.html
web/plates/traffic-help.html
web/plates/traffic.html

Fixes for #251 and #254.
- Traffic "last seen" time is now changed to a traffic age, set by the internal Stratux `monotonic` timer.
- traffic.go JSON calls updated to refresh all traffic once per second, even if postion hasn't been updated.
- New ti.Timestamp and ti.Age variables added to traffic.go
- Timeout for sending GDL90 traffic message reduced to 6 seconds. Traffic will remain in internal database and on web UI for 60 seconds.
- Minor GPS improvements related to time parsing
- Added clock to web UI status page.
- Update status UI to reflect new features added over the past few months

Traffic UI and other improvements

---

main/sdr.go

When I added error checking on the regexps I introduced a bug due to incorrect logic. Sorry about that.

Fixed a bug from #248

---

main/ry835ai.go
web/plates/js/traffic.js

- Fix a bug in #259 where traffic targets 59.x seconds old are not removed from web UI
- Fix a malformed time string when setting date / time from the RMC GPS message

Bug fixes for traffic UI and setting GPS time

---

main/traffic.go
web/css/main.css
web/plates/js/traffic.js
web/plates/traffic.html

Requested at https://redd.it/46hmso
This update passes `ti.Addr_type` to the web UI to support showing whether traffic messages originated from ADS-B air-to-air broadcasts, or from TIS-B ground-to-air broadcasts. Currently, this is supported only for UAT traffic, as the dump1090 output on port 30003 does not pass this status. 
Traffic reports originating at the GBTs are indicated with a lighter highlight color and a satellite dish symbol. Airborne reports use the existing color and get an airplane symbol.

Show traffic source (ADS-B vs TIS-B) in web UI

---

init.d-stratux

This change might prevent another update*.sh script from being executed since it is just looking in the root directory for the latest file with the word update. 
This would require naming the update the same update\*stratux\*v*.sh
i.e.: update-stratux-v0.7b4-f98a8d58c6.sh
Just a bit more safety...

Change to be more specific in choosing update file

---

main/gen_gdl90.go
main/sdr.go

This fixes/simplifies the handling of anonymous and tagged dongles.

better anonymous & tagged dongle handling, sdr file cleanup

---

.gitmodules
main/gen_gdl90.go
main/traffic.go

Add Stratux-specific branch of MalcolmRobb/dump1090 and overhaul the traffic.go parsing routines.
**Dump1090 changes:**
- Add parsing of 1090ES TIS-B messages
- Add parsing of ADS-B / ADS-R / TIS-B NACp category from DF=17, TC=29/31 and DF=18, TC=19 messages
- Add parsing of GNSS altitude flag
- Add parsing of delta height between GNSS altitude and baro altitude
- New JSON-formatted output of fields used by traffic.go are sent on TCP port 30006. These include additions for NACp, signal strength, delta height, and GNSS height flag as noted in the [dump1090 README](https://github.com/AvSquirrel/dump1090#port-30006).
**Stratux changes:**
1090 ES parsing is completely overhauled to support the new dump1090 format. Additional ES parsing changes include:
- dump1090 raw signal strength is …

Dump1090 improvements. Overhauled traffic parsing. UAT groundspeed and air/ground status bug fixes.

---

.gitignore
main/sdr.go

When a dongle has failed catastrophically we assume ReadSync fails for UAT and we get stderr output for ES.

 when a dongle fails then close its process, ES read stdout/stderr simplified, update gitignore

---

web/plates/js/status.js

Calculate days, hours, minutes, and seconds of uptime and then display the uptime in the format d/hh:mm:ss.

Update status.js to repair issue #299.

---

image/spindle/wheezy-stage4
main/gen_gdl90.go
main/managementinterface.go
web/js/main.js

this removes gen_gdl90 from service the basic WebUI. gen_gdl90 still provides its web services and websockets - now on port 8080.
`http://192.168.10.1` will return the Stratus WebUI
`http://192.168.10.1:8080/getSettings` will return the stratux settings JSON
Spindle will install `lighttpd`, add a symlink to access logs, and then enable support for directory lists and smlinks so the log page still works.

use standalone httpd service / move stratux services to port 8080

---

image/hostapd.conf

as per reading the default hostapd conf file, settings for ieee80211n=1 requires wmm_enabled to be set, not wme_enabled.
ieee80211n: Whether IEEE 802.11n (HT) is enabled
0 = disabled (default)
1 = enabled
Note: You will also need to enable WMM for full HT functionality.
Note: hw_mode=g (2.4 GHz) and hw_mode=a (5 GHz) is used to specify the band.
ieee80211n=1

fix wmm parameter name

---

image/stratux-wifi.sh

Allows an RPi2 or RPi0 to use a non Edimax Wifi dongle provided it's natively supported.

image: add rpi0 and explicit edimax dongle check

---

circle.yml

Currently when PRs hit circleci the actual PR branch that's submitted isn't being built due a PR branch naming conflict, circle tags PRs with pull/XXX whereas git has them listed as pr/XXX, this PR adjusts pull/XXX to pr/XXX.
I deleted the previous PR's branch during branch cleanup.

circleci: allows PRs to correctly build themselves when the PR happens

---

Makefile

goroot is a vestige of the past, http://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really

check for the go command not GOROOT

---

main/gen_gdl90.go

Casting GPS altitude to int16 before encoding to 5-foot increments caused overflow (negative altitudes) above 32767 (0x7FFF) feet. Addresses #373.

Fix geometric ownship alt overflow

---

main/datalog.go
main/monotonic.go

Referenced in #372.
`dataLogTimestamps` is a golang map. The map type is not threadsafe, and requires synchronization of all writers and readers. In this application, not providing mutex sync around all readers still allowed gen_gdl90 to randomly crash, and adding full protection caused too many deadlocks.
This PR changes `dataLogTimestamps` to a more conventional array / slice. This makes more sense for how it's being used (storing a series of sequential timestamp structures). It doesn't need synchronization if we're not removing values, and appends seem to be faster than map inserts -- this speeds up the SQLite logging.

SQLite logging - Change dataLogTimestamps[] to slice

---

main/gen_gdl90.go
main/ry835ai.go

- `mySituation.TrueCourse` is stored as an int, even though GPS provides Course Over Ground with two places of precision beyond the decimal. This changes `TrueCourse` to a `float32` to preserve this information, and therefore eliminate up to 1 degree of track error.
- Reduce the quantization error when converting `mySituation.TrueCourse` to GDL90 8-bit `tt` track. This will provide more accurate track data in the GDL90 messages. (#368)
- Add periodic polling of free / used disk space to `globalStatus` and stratux.log.
- Remove extraneous newline in `printStats()`

Improve ownship track accuracy. Add disk usage to logs.

---

Makefile
main/datalog.go
main/equations.go
main/traffic.go

This PR covers a few improvements to the traffic backend, and will be the first of a few smaller PRs referenced in yesterday's comments on #340:
- Updated dump1090 to include latest commits to the main dump1090-mutability fork
- Add equations.go library for great circle distance / bearing (and eventual use for GPS pseudoattitude / AHRS improvements)
- Calculate great circle distance and bearing to traffic targets
- Add squawk codes for Mode S targets
- Move SQLite logging of the raw port 30006 dump1090 JSON messages to a new table
- SQLite logging of dump1090 console only when globalSettings.DEBUG = true and recordLogs = true to save disk space
- SQLite logging of decoded traffic information reduced to once per second, when each `ti` is sent to the GDL90 output. This will cut down on …

Traffic backend updates

---

image/config.txt
main/ry835ai.go
test/mtk_config.sh

- Resolves #393 by removing `/dev/ttyS0` from GPS initialization sequence. On the RPi 3, this port does *not* connect to GPIO pins 8 and 10; receivers connected to these pins are therefore not detected.
- Add a interactive script for configuring MTK3339 GPS receivers from the command line

GPS UART fix for RPi 3

---

test/sirf_config.sh

This is a configuration shell script for the BU-353-S4. It's similar in construction to the script I created for MTK3339 (see #394) and can be run offline (i.e. without gen_gdl90 running)  to help resolve configuration problems.
Invoke as `./test/sirf_config.sh`.
It assumes that there is a SIRF IV receiver connected to `dev/ttyUSB0`. It starts by sending commands to:
- Reset baud rate to the factory default of 4800 bps
- Reset message rate to once per second
- Turns off all messages except GPRMC
Quitting at that point leaves the receiver in a developer-friendly "safe mode": low bitrate and low message frequency. Otherwise, the user is prompted to press a key to continue with the Stratux-specific setup:
- Receiver and port baud rate set to 38400 bps
- WAAS enabled
- GGA, RMC, VTG messages …

Shell script for offline SIRF-IV / BU-353-S4 configuration

---

main/gen_gdl90.go
main/ry835ai.go

A few incremental improvements to GPS subsystem:
- Prioritize `/dev/ttyACM0` over `/dev/ttyUSB0` at startup. This will allow the simultaneous use of u-blox receivers over their native USB connection, while having a USB-to-serial bridges installed.
- 'isGPSValid()' now checks for a connected GPS device, and that the "quality" byte is greater than zero. This should prevent invalid positions (e.g. off the coast of Equatorial Guinea, 0°N / 0°W) from being used for traffic distance calculations at startup.
- Changed UI description for `quality==2` solution from "DGPS (SBAS / WAAS)" to "GPS + SBAS (WAAS / EGNOS)". While satellite-based augmentation is a differential method, "DGPS" more commonly refers to terrestrial differential corrections. The new description is more accurate for 99.9% of …

GPS backend improvements

---

main/datalog.go
main/gen_gdl90.go
main/managementinterface.go
main/traffic.go
web/plates/js/settings.js
web/plates/settings.html

- Add watchdog function and quitchannel controls for graceful shutdown and restart of sqlite logs. Log may now be started and stopped at any time.
- SQLite system now only runs when `globalSettings.ReplayLog == true`.
- SQLite database is safely and properly closed when log system is closed.
- globalStatus and globalSettings are only sent to log when `globalSettings.ReplayLog == true`
- Display of traffic source in callsign now split out from verbose 'DEBUG' setting

Graceful shutdown of SQLite logs

---

Makefile
image/10-stratux.rules
main/ry835ai.go

- Add udev rule for u-blox 8 devices (RY835, RY836AI) connected over USB
- Use generic descriptions for the u-blox 6 and 7 chipsets, rather than vendor-specific GPS models. 
- Add udev rules to Makefile. This will allow udev configuration to be updated through `git pull` / `make install`.

Udev updates

---

main/gen_gdl90.go
main/managementinterface.go
uatparse/uatparse.go

This is a rollup of stability improvements tested in conjunction with #420. Includes:
- Mutex protection for an unprotected `map[string]ADSBTower `
- Removes a currently unused `products_last_minute` map type
- Array bounds checking on uatdecode.go `DecodeUplink()` function
- Array bounds checking on the (now disabled) `decodeAirmet()` function

Additional UAT stability improvements (tower mutex, array bounds checks)

---

main/gen_gdl90.go

Commit 404a4c9c0 introduced a bug that broke logging for non-FlightBox hardware.
If FlightBox wasn't detected, `debugLogf` `dataLogFilef` were never assigned and remained as nulls. Consequently, the SQLite log and message log were never written to disk, and an error was thrown on the UI status page.

Bug fix for logging

---

main/traffic.go
test/icao2reg.go
web/plates/js/traffic.js
web/plates/traffic.html

There was some discussion a few months back (#298) about goofy callsigns being transmitted by certain aircraft: "00000000", "N", and everyone's favorite, "BWIFATTY". Consensus was that those callsigns were intentionally entered into the FMS by their flightcrews, and there was some discussion about either filtering "unusual" callsigns, or translating the Mode S code to determine the actual tail number. This is an implementation of the latter.
In both the United States and Canada, civil aircraft registrations (N-number and C-numbers) are related to the 24-bit Mode S code through a 1-to-1 mathematical relationship. In other words, given a specific 24-bit code, it is possible to determine what tail number it belongs to, and vice versa.
The method for calculating US/CAN registrations is …

Automatic translation of Mode S codes to US/CA tail numbers

---

image/mkimg.sh
selfupdate/update_footer.sh

See #400.
This updates two setup scripts (mkimg.sh and update_footer.sh) to look for and remove any `console=ttyAMA0` references in `/boot/cmdline.txt`, resolving a serial connection issue that caused USB receivers to be unable to connect if installed after boot, and for intermittent disconnects of GPS receivers connected over serial GPIO. 
This also removes an outdated reference to `/etc/inittab` in mkimg.sh.

Update setup scripts to disable console on ttyAMA0

---

main/gen_gdl90.go
web/plates/js/status.js
web/plates/status.html

This is a really simple tweak based on something I noticed in my testing use case.
I've been doing some device testing, and it's useful to know the accuracy of the GPS without tapping around and losing the ability to see messages/min for UAT/1090, etc.
This adds `mySituation.Accuracy` to the output of `updateStatus`, and handles it on the front end. To keep from linewrapping on small screens, I simplified `WAAS / EGNOS` to just `WAAS`, although I could see this being less than good. If it's requested, I can probably fiddle with the layout of that component and create more space on the values side; there's room to take away from the labels.
I'm new to playing around in the angular side - let me know if I'm doing Bad Things by manipulating this into a String or something!

GPS accuracy on Status page

---

main/gen_gdl90.go
web/plates/js/status.js
web/plates/status.html

This removes the clock from the UI (js, template) and the .go status result, part of enhancement #426.

Clean out clock UI

---

image/stxAliases.txt

The image has a typo in the aliases for the setSerial1 alias.

Fixed typo in aliases for setSerial1

---

selfupdate/update_footer.sh

this was preventing the stxAliases.txt from being copied over properly

Fixed typo

---

main/network.go

This adds the ability to have static IP hosts. I frequently use the stratux with an ethernet adapter, thus having this feature will really speed up development for me, and also allows to have a stratux to be connected on a wired network. The file /etc/stratux-static-hosts.conf would contain lines as such:
192.168.0.2 host1
192.168.0.3 host2
and this would then be appended to the dhcp client list.

Added ability to have static IP hosts

---

web/plates/js/weather.js

The WINDS forecast will show 'from now' instead of '29 days ago'. It may not be the right solution, but at least this is a good placeholder for a change

Possible solution for upper level winds forecast time

---

Makefile
image/10-stratux.rules
main/gen_gdl90.go
main/gpsd.go

This is a basic hack to pull GPS information from gpsd.  There seemed to be some interest in assessing the usefulness of gpsd, so I created this as an excuse to learn Go and play with gpsd.  This is my first Go project so any feedback is appreciated.  If anyone can think of any features that might help with assessment, please let me know.
To run this you will need to connect your Pi to the internet, `apt-get install gpsd gpsd-clients`, and enable/start the service.
Some initial observations:
- GPS hotplug works great.  Basically a non-issue on the stratux level.
- It will take data from more than one GPS, however, there is not (currently) any code for selecting which report to use.  Whatever is the latest to be received is what is used.
- The gpsd shipping with Raspbian Jessie (3.11) does …

RFC: gpsd evaluation

---

main/managementinterface.go
main/network.go

This encapsulates GDL90 traffic over a websocket for broadcasting to remote hosts. The remote host can connect to a stratux over the internet and receive the GDL90 to be rebroadcasted on its local network over UDP. This will be used for remote developers so they can use a remote stratux for software development of Android or iPad applications using real data.

GDL90 JSON interface stratux changes

---

main/gpsd.go
main/ry835ai.go
web/plates/gps.html
web/plates/js/gps.js

* Rename up SatelliteNMEA to Prn, as this field has contained the PRN
* Fix double conversion bug since SKY reports should already be PRN instead of NMEA ID.
* Fix sortation in satellite list by populating the Prn field.
* Set mySituation.Quality to 2 if there is a SBAS PRN satellite in solution
If gpsd is in ublox protocol mode, it will mark the satellite as "in solution" if the PRN is the same as reported by a NAV-SBAS message.  So for ublox device this should be a reliable way to detect WAAS.

Gpsd SBAS detection

---

main/gen_gdl90.go
main/gpsd.go
main/managementinterface.go

* Monitor gpsd connection failures and automatically reconnect
* Add stratux.conf setting to use a different gpsd server.  Advanced users can use a gpsd on another machine.
* User controls connection from management interface using GPS on/off toggle.  If gpsd has no clients, it will disconnect from the device.  Supposedly this can save power on some devices.
* Log individual gpsd messages only in verbose mode.
The requires the latest version of [stratux/go-gpsd](https://github.com/stratux/go-gpsd)

Gpsd connection management

---

__root__stratux-pre-start.sh
image/hostapd-edimax.conf
image/hostapd.conf
image/hostapd.user
image/hostapd_manager.sh
image/stratux-wifi.sh
selfupdate/makeupdate.sh

I have changed the code to use hostapd.user, which contains all the user configurable values and modified stratux-pre-start.sh and stratux-wifi.sh to create /tmp/hostapd.conf on the fly by merging the standard /etc/hostapd/hostapd.conf(or hostapd-edimax.conf if pi2) and /etc/hostapd/hostapd.user to build the /tmp/hostpad.conf.
This allows us to overwrite the /etc/hostapd.conf(or hostapd-edimax.conf) whenever we need and keep any user values.
The changes also will create the hostapd.user file if it does not exist and move all the user configurable settings into it. 
I also changed my hostapd_manager.sh to work on hostapd.user now

Move user configurable options out of hostapd.conf and hostapd-edimax.conf to hostapd.user and build temp hoatapd.conf on the fly with stratux-wifi.sh

---

web/plates/traffic-help.html

Added additional information to traffic-help.html to include the prefix
used when Show Traffic Source In Callsign is enabled within the
settings.
It was difficult to locate the definitions of each of the traffic type
prefixes, so I thought the help page would be a good location to define
these.
Additionally adjusted some spacing of the list elements to provide
easier readability on this help page.

Added traffic type prefix definitions to traffic-help.html

---

main/gen_gdl90.go
main/managementinterface.go
main/network.go
notes/app-vendor-integration.md
web/plates/js/settings.js
web/plates/settings.html

1) Added the ability to add a space separated list of IP's that will be sent network data for use when testing while connected to a network other than the Raspberry PI Network.  I did see that a file could be created that contained those IP's but this seems easier.  (only visible when DeveloperMode is enabled)
2) Removed Windows characters from settings.js,  (didn't want them to be inconsistent and was editing on the Raspberry PI not on Windows. 
3) Display Raw Configuration when DeveloperMode is set.

Add ability to set static ip from web ui when in dev mode

---

notes/app-vendor-integration.md

github markdown `json` format doesn't accept comments; but luckily `javascript` format does. This change makes the docs look nice in github.

[docs] change snippet to 'javascript' for github markdown

---

main/gps.go
main/sensors.go

Minor fix to address https://github.com/cyoung/stratux/issues/705.  I don't know of any EFB's that use AHRSGyroHeading, so validated that behavior is now as expected using a gdl90 udp stream listener.

Fix gdl90 AHRSGyroHeading reporting.

---

main/gen_gdl90.go

**Description**
The Ownship information is currently being sent with a target identity of 0x01 which represents 'No Traffic Alert' and 'ADS-B with Self Assigned Address'.  Foreflight users taking advantage of Mode S Code configuration for passing Ownship information to Foreflight for track logs and draft logbook entries, will experience Foreflight reporting no Ownship detection.  Latest Foreflight version appears to ignore Ownship information when the target identify of 0x01 is being passed.
**What Is Changing**
Update Ownship target identity to report 0x00 which represents 'No Traffic Alert' and 'ADS-B with ICAO'.  This will allow Foreflight to report Ownship Detection and list the aircraft Tail Number correctly.
**Pre-Testing**
1. Assign ICAO code in Mode S Code configuration input box …

Fix Ownship Target Identity Information

---

main/gen_gdl90.go
main/network.go

Added a configuration parameter called "NoSleep" that disables client sleeping when enabled. This change will allow data transmission to broadcast addresses as well as clients who do not respond to a ping requests.

Added setting "NoSleep" to disable sleeping

---

main/gps.go
web/plates/gps.html
web/plates/js/gps.js

AHRS calculation used to be inside `calcGPSAttitude()` which is no longer being called when IMU is enabled. This PR moves the calculation code to a dedicated function to ensure nav rate can still be displayed in IMU AHRS mode to help evaluating GPS performance.
Also includes changes from #597

Added nav rate display and Galileo nav rate change for AHRS branch.

---

main/sensors.go
sensors/bmx160.go

This PR adds support for the BMX160 accel/gyro chip.  Must be accompanied by PR for cyoung/goflying.

Add support for bmx160 MPU
